config/routes.rb
Rails.application.routes.draw do
  resources :items
  root 'welcome#index'
  get 'pruebas' => 'welcome#pruebas'
end

app/models/item.rb
class Item < ActiveRecord::Base
  validates :title, presence: true
  validates :comun, presence: true
  # TODO Limitar la longitud de los campos title, comun, python , ruby
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }

  validates :name, presence: true, length: { maximum: 50 }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, 
        presence: true, 
        length: { maximum: 255 }, 
        format: { with: VALID_EMAIL_REGEX }, 
        uniqueness: {case_sensitive: false}
        
    has_secure_password
    
  # Refuerzo de la contraseña
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :time_set
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def time_set
    @hora = Time.now
    @horajs = @hora.strftime("%m/%d/%Y %I:%M %p UTC")
    @admin = params["admin"]
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.paginate(page: params[:page], :per_page => 5)
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :comun, :python, :ruby)
    end
    
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def pruebas
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
class CodeRayify < Redcarpet::Render::HTML
  def block_code(code, language)
    CodeRay.scan(code, language).div
  end
end

def markdown(text)
  coderayified = CodeRayify.new(:filter_html => true, 
                                :hard_wrap => true)
  options = {
    :fenced_code_blocks => true,
    :no_intra_emphasis => true,
    :autolink => true,
    :lax_html_blocks => true,
  }
  markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
  markdown_to_html.render(text).html_safe
end

def is_admin?
  # return @admin == "108727"
  return true 
end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container-fluid">
    <div class="field row">
      <br>
      <%= f.text_field :title, placeholder: "<Título para nuevo concepto aquí>", class: "text-primary" %>
    </div>
    <div class="row">
      <div class="field col-md-4 tag-comun">
        <%= f.text_area :comun, placeholder: "<Información general aquí>" %>
      </div>
      <div class="field col-md-4 tag-python">
        <%= f.text_area :python, placeholder: "<Información y ejemplos Python aquí>" %>
      </div>
      <div class="field col-md-4 tag-ruby">
        <%= f.text_area :ruby, placeholder: "<Información y ejemplos Ruby aquí>" %>
      </div>
    </div>
    <div class="actions row center">
      <%= f.submit "Actualizar", class: "btn btn-danger extrawidth" if is_admin? %>
    </div>
  </div>
<% end %>

app/views/items/edit.html.erb
<div class="table-container">
<h1>Editando concepto &nbsp;<%= link_to 'Volver', items_path, :class => "btn btn-primary" %> <%= link_to 'Mostrar', @item, class: "btn btn-primary" %></h1>

<%= render 'form' %>
</div>
<div class="table-container center">

</div>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<div class="table-container">
<h1>Listado de conceptos 
<%= link_to 'Añadir', new_item_path, class: "btn btn-primary" if is_admin? %>
</h1></div>

<div class="table-container">

<%= will_paginate %>

<div>
  <div>
    <% @items.each do |item| %>
      <div class="row titulo">
        <div class="col-md-12 text-primary"><h3><%= item.title %>&nbsp;<small><%= link_to "Ampliar", item, class: "btn btn-info btn-xs" %></small></h3>
       
          <%
          # = link_to 'Mostrar', item, class: 'btn btn-primary btn-xs' 
          %>
        </div>
        
      </div>
      <div class="row">
        <div class="col-md-4 fading-row"><%= markdown(item.comun) %></div>
        <div class="col-md-4 fading-row python-tab"><%= markdown(item.python) %></div>
        <div class="col-md-4 fading-row ruby-tab"><%= markdown(item.ruby) %></div>
        <div class="menusito">
          <%= link_to 'Editar', edit_item_path(item), class: 'btn btn-primary btn-xs' if is_admin? %>
          <%= link_to 'Borrar', item, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' if is_admin? %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<%= will_paginate %>

</div>

app/views/items/new.html.erb
<div class="table-container">
<h1>Nuevo concepto &nbsp;<%= link_to 'Back', items_path, class: "btn btn-primary" %>
</h1>

<%= render 'form' %>

<div class="table-container center">
</div>
</div>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<div class="table-container table-container-header"><h1 class="text-primary"><%= @item.title %>
&nbsp;<%= link_to 'Volver', items_path, class: "btn btn-primary" %></h1></div>

<div class="table-container">
<div class="table">
  <div class="row">
    <div>
      <div class="col-md-4 comun-tab"><%= markdown(@item.comun) %></div>
      <div class="col-md-4 python-tab"><%= markdown(@item.python) %></div>
      <div class="col-md-4 ruby-tab"><%= markdown(@item.ruby) %></div>
    </div>
  </div>
</div>
</div>

<div class="table-container center">
<%= link_to 'Editar', edit_item_path(@item), class: "btn btn-primary" if is_admin? %> 
<%= link_to 'Volver', items_path, class: "btn btn-primary" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dezero</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>
</head>
<body onload=display_ct();>

<nav class="navbar navbar-default">
  <div class="container-fluid bg-primary">
    <div class="navbar-header">
      <%= image_tag("favicon.ico", alt: "logo", class: "logo") %>
      <%= link_to "Diccionario Python/Ruby", root_path, class: "navbar-brand" %>
    </div>
    <div>
      <ul class="nav navbar-nav">
        <li><%= link_to "Principal", root_path %></li>
        <li><a href="/items">Listados</a></li>
        <li><a href="#">Búsqueda</a></li>
        <li><a href="#">Contacto</a></li>
      </ul>
    </div>
  </div>
</nav>

<%= yield %>

<footer>
  <div>
    <span id='ct'/>
  </div>
      <%= debug(params) if Rails.env.development? %>
</footer>

</body>
</html>

app/views/welcome/index.html.erb
<div class="container">
  <h1>Diccionario Python/Ruby</h1>
  <p>Esta web es un ejercicio de programación en Ruby on Rails. La idea es 
  crear una base de datos de conceptos comunes para consultar cuando uno no
  se acuerda de la sintaxis correcta en uno u otro idioma.</p>
  <h2>Cosas pendientes de hacer:</h2>
  <ol>
    <li>Modelar usuarios, con activación por email</li>
    <li>Habilitar la edición selectivamente</li>
    <li>Crear diccionarios de usuario, donde uno tenga conceptos particulares</li>
    <li>Hacer copia de seguridad de la base de datos</li>
    <li>Crear una estructura de datos que permita añadir más lenguajes y seleccionar los que se desea comparar</li>
  </ol>
</div>

app/views/welcome/pruebas.html.erb
<div class=" table-container">

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Home</a></li>
    <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Profile</a></li>
    <li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">Messages</a></li>
    <li role="presentation"><a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">Settings</a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane fade in active" id="home">...</div>
    <div role="tabpanel" class="tab-pane fade" id="profile">
      <%= markdown("""
En **Python 2** `print` es una instrucción, y no usa paréntesis. Si usas paréntesis, entenderá que estás mostrando una tupla de varios elementos, con sus paréntesis incluídos.

En **Python 3**, `print()` es una función y los paréntesis son obligatorios.

En **Ruby** tenemos dos métodos, `puts`y `print`. El primero acaba con un carácter de nueva línea (CRLF), el segundo no. Con este último, por tanto, pueden concatenarse varias cadenas en una misma línea.
""".html_safe) %>
    </div>
    <div role="tabpanel" class="tab-pane fade" id="messages">
            <%= markdown("""
#### Python 2

```python
a = 'Hola'
b = 'amigos'
c = 'míos'
print a, b; print c
# Hola amigos
# míos
```

Si se añade una coma al final, suprime el CRLF (*carácter de nueva línea*).

```python
print a, b; print c
# Hola amigos míos
```
#### Python 3 

La forma de evitar el CRLF es diferente. Se le pasa el parámetro `end` para indicarle que el carácter de fin de línea es la cadena vacía:

```python
print(a, b, end=""); print(c)
# Hola amigosmíos
```

Fíjate que hemos perdido el espacio que teníamos por defecto (puede añadirse poniendo `end=" "`)""".html_safe) %>

    </div>
    <div role="tabpanel" class="tab-pane fade" id="settings">
            <%= markdown("""
La diferencia entre las instrucciones **puts** y **print** es que la primera incluye un CRLF (*carácter de nueva línea*) mientras que el segundo no. De este modo, a base de **print** consecutivos se puede completar una línea por partes.

```ruby
a = 'Hola'
b = 'amigos'
c = 'míos'
puts a, b, c`
# => 'Holaamigosmíos'
```

```ruby
puts 'HOLA'; puts 'ADIOS'
# => HOLA
# ADIOS

print 'Hola'; print 'amigos'; print 'míos'
# => Holaamigosmíos
```""".html_safe) %>

    </div>
  </div>

</div>